# Generated by Django 6.0.1 on 2026-01-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
