# Generated by Django 6.0.1 on 2026-01-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketstatus',
            unique_together={('board', 'name')},
        ),
    ]
