# Generated by Django 6.0.1 on 2026-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_alter_ticketstatus_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatus',
            name='colour',
            field=models.CharField(choices=[('grey', 'Default'), ('green', 'Green'), ('turquoise', 'Turquoise'), ('blue', 'Blue'), ('light-blue', 'Light Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow')], default='grey', max_length=10),
        ),
    ]
